### ISSUE TITLE
cd: help debugging connection to database error

### ISSUE THREAD

**Issue by shoriwe** [hawks-atlanta/metadata-scala#60]
Currently the service deployment is returning (this is the entire log):

```
Exception in thread "main" org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://postgresql-ha-pgpool:5432/capyfile
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1065)
        at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:621)
        at org.hawksatlanta.metadata.migrations.PostgreSQLMigration$.migrate(PostgreSQLMigration.scala:14)
        at org.hawksatlanta.metadata.Main$.main(Main.scala:8)
        at org.hawksatlanta.metadata.Main.main(Main.scala)
```
Any idea why this could be happening (using `main`) does this is already patched in `dev`?

**Comment by shoriwe** [comment]
Current environment variables during deployment:

- `DATABASE_HOST`: `postgresql-ha-pgpool`
- `DATABASE_PORT`: `5432`
- `DATABASE_NAME`: `capyfile`
- `DATABASE_USER`: THIS FIELD SHOULD NOT BE SHARED
- `DATABASE_PASSWORD`: THIS FIELD SHOULD NOT BE SHARED

**Comment by shoriwe** [comment]
Could this be relevant [docs](https://jdbc.postgresql.org/documentation/datasource/)?

**Comment by shoriwe** [comment]
You can debug locally with:

```yaml
version: '3.1'

services:
  metadata:
    image: ghcr.io/hawks-atlanta/metadata-scala:latest
    container_name: metadata
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DATABASE_HOST: "postgres-db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "metadata"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metadata
 ```

**Comment by shoriwe** [comment]
@PedroChaparro let me know if I'm missing something during deployment

**Comment by PedroChaparro** [comment]
> Any idea why this could be happening (using `main`) does this is already patched in `dev`?

Shouldn't happen, it isn't a known bug. I'm checking it 👀 .

**Comment by PedroChaparro** [comment]
@shoriwe Seems to be [an error with the `.jar` file](https://github.com/flyway/flyway/issues/3722). I'll try with older versions.

**Comment by PedroChaparro** [comment]
@shoriwe Got it, thanks for reporting. Check #61
